config/routes.rb
Rails.application.routes.draw do
  


  root 'pages#home'

  devise_for  :users, 
              :path => '', 
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:show]
  resources :homes
  resources :photos

  resources :homes do 
  	resources :swaps, only: [:create]
  end

  get '/preload' => 'swaps#preload'
  get '/preview' => 'swaps#preview'

  get '/your_trips' => 'swaps#your_trips'
  get '/your_swaps' => 'swaps#your_swaps'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :swaps

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :accommodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 500}
  validates :address, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :home
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/swap.rb
class Swap < ApplicationRecord
  belongs_to :user
  belongs_to :home
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable
  validates :fullname, presence: true, length: {maximum: 50}

  has_many :homes 
  has_many :swaps
  
  def self.from_omniauth(auth)
  	user = User.where(email: auth.info.email).first

  	if user
  		return user
  	else
  		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  			user.fullname = auth.info.name
  			user.provider = auth.provider
  			user.uid = auth.uid
  			user.email = auth.info.email
  			user.image = auth.info.image
  			user.password = Devise.friendly_token[0,20]

  		end
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
		devise_parameter_sanitizer.permit(:account_update, keys: [:fullname])
  	end	
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  #before_action :set_home, only: [:show, :edit, :update]
  #before_action :authenticate_user!, except: [:show]

  def index
   @homes = current_user.homes
  end

  def show
     @photos = @home.photos
  end

  def new
    @home = current_user.homes.build 
    
  end

  def create
    @home = current_user.homes.build(home_params)


    if @home.save

      if params[:images]
        params[:images].each do |image|
          @home.photos.create(image: image)
        end
      end

      @photos = @home.photos
      redirect_to edit_home_path(@home), notice: "Saved.."
    else
      render :new
    end
  end

  def edit
    if current_user.id == @home.user.id
      @photos = @home.photos
    else
      redirect_to root_path, notice: "You don't have permission"
    end
  end

  def update
    if @home.update(home_params)

      if params[:images]
        params[:images].each do |image|
          @home.photos.create(image: image)
        end
      end


      redirect_to edit_home_path(@home), notice: "Updated.."

      
    else
      render :ender
     end
  end

  private
    def set_home
      @home = Home.find(params[:id])
    end

    def home_params
      params.require(:home).permit(:home_type, :accommodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_air, :is_heating, :active)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	def facebook
		@user = User.from_omniauth(request.env["omniauth.auth"])

		if @user.persisted?
			sign_in_and_redirect @user, :event => :authentication
			set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
		else
			session["devise.facebook_data"] = request.env["omniauth.auth"]
		redirect_to new_user_registration_url
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

	def destroy
		@photo = Photo.find(params[:id])
		home = @photo.home

		@photo.destroy
		@photos = Photo.where(home_id: home.id)

		respond_to :js
	end
end

app/controllers/swaps_controller.rb
class SwapsController < ApplicationController
	before_action :authenticate_user! 
	
	def preload
		home = Home.find(params[:home_id])
		today = Date.today
		swaps = home.swaps.where("start_date >= ? OR end_date >= ?", today, today)

		render json: swaps 
	end

	def preview
		start_date = Date.parse(params[:start_date])
		start_date = Date.parse(params[:end_date])

		output = {
			conflict: is_conflict(start_date, end_date)
		}

		render json: output 
	end

	def create
		@swap = current_user.swaps.create(swap_params)

		redirect_to @swap.home, notice: "Your swap has been requested"
	end

	#def your_trips
	#	@trips = current_user.swaps 

	#end

	#def your_swaps 
	#	@homes = current_user.homes
	#end

	private

		def is_conflict(start_date, end_date)
			home = Home.find(params[:home_id])

			check = home.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
			check.size > 0? true : false 
		end
		
		def swaps_params
			params.require(:swap).permit(:start_date, :end_date, :home_id)
		end
end 

app/helpers/application_helper.rb
module ApplicationHelper

	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		if user.image
			user.image
		else
		"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
		end
	end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/homes/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
	Create your home 

	</div>
	<div class="panel-body">
		<div class="container">


		<%= form_for @home, html: {multipart: true} do |f| %>
			

			<div class="row">
				<div class="col-md-4 select">
					<div class="form-group">
					<label>Home Type</label>
					<%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"]], id: "home_type", prompt: "Select", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
					<div class="form-group">
						<label>Accommodate</label>
						<%= f.select :accommodate, [["1", 1], ["2", 2], ["3", 3], ["4", 4]], prompt: "Select", class: "form-control" %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4 select">
					<div class="form-group">
					<label>Bedrooms</label>
					<%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]], prompt: "Select", class: "form-control" %>
					</div>
				</div>

				<div class="col-md-4 select">
					<div class="form-group">
						<label>Bathrooms</label>
						<%= f.select :bath_room, [["1", 1], ["2", 2], ["3+", 3]], prompt: "Select", class: "form-control" %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Listing name</label>
					<%= f.text_field :listing_name, placeholder: "Be clear and descriptive", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Summary</label>
					<%= f.text_field :summary, rows: 5, placeholder: "About your home", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="form-group">
					<label>Address</label>
					<%= f.text_field :address, placeholder: "Address", class: "form-control" %>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<%= f.check_box :is_air %> aircon
					</div>
					<div class="form-group">
						<%= f.check_box :is_heating %> heating
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="form-group">
						<span class="btn btn-default btn-file">
							<i class="fa fa-cloud-upload fa-lg"></i>Upload Photos 
								<%= file_field_tag "images[]", type: :file, multiple: true %>
						</span>
					</div>
				</div>

			</div>

			<div id="photos"><%= render 'photos/list' %></div>

			<div class="row">
				<div class="form-group">
					<%= f.check_box :active %> Active
				</div>
			</div>

			<div class="actions">
				<%= f.submit "Save", class: "btn btn-primary my-button" %>
			</div>

		<% end %>
		</div>
	</div>
</div>

app/views/homes/create.html.erb
<h1>Homes#create</h1>
<p>Find me in app/views/homes/create.html.erb</p>

app/views/homes/edit.html.erb
<%= render 'form' %> 

app/views/homes/index.html.erb
<div class="row">
	<div class="col-md-3">
	<ul class="sidebar-list">
		<li class="sidebar-item"><%= link_to "Your Listing", homes_path, class: "sidebar-link active" %>
		</li>
		<li class="sidebar-item"><%= link_to "Your Swaps", homes_path, class: "sidebar-link active" %>
		</li>
	</ul>
	</div>

	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
			Listings
			</div>
			<div class="panel-body">
				<% @homes.each do |home| %>
					<div class="row">
						<div class="col-md-2">
							<%= image_tag home.photos[0].image.url(:thumb) if home.photos.length > 0 %>
						</div>
						<div class="col-md-7">
							<%= home.listing_name %>
						</div>
						<div class="col-md-3 right">
							<%= link_to "Update", edit_home_path(home), class: "btn btn-primary my-button" %>
						</div>
					</div>
					<hr>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/homes/new.html.erb
<%= render 'form' %> 

app/views/homes/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">

		<!--image-->
		<div class="row">
			<div class="col-md-12">
			<%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
			</div>
		</div>
	</div>

	<br>
	<!-- main info -->
	<div class="row">
		<div class="col-md-8">
			<div class="row">
				<div class="col-md-3 text-center">
				<%= image_tag avatar_url(@home.user), class: "img-circle avatar-large" %> <br><br>
				<%= @home.user.fullname %>
				</div>

				<div class="col-md-9" id="listing-title">
					<h4><%= @home.listing_name %></h4>
					<%= @home.address %>
					<hr>
					<div class="row text-center row-space-1">
						<div class="col-sm-3">
							<i class="fa fa-home fa-2x"></i>
						</div>

						<div class="col-sm-3">
							<i class="fa fa-users fa-2x"></i>
						</div>

						<div class="col-sm-3">
							<i class="fa fa-bed fa-2x"></i>
						</div>

						<div class="col-sm-3">
							<i class="fa fa-ship fa-2x"></i>
						</div>
					</div>

					<div class="row text-center">
						<div class="col-sm-3">
							<%= @home.home_type %>
						</div>
						<div class="col-sm-3">
							<%= @home.accommodate %> <%= @home.accommodate > 1? "Guests" : "Guest" %>
						</div>
						<div class="col-sm-3">
							<%= @home.bed_room %> <%= @home.bed_room > 1? "Bedrooms" : "Bedroom" %>
						</div>
						<div class="col-sm-3">
							<%= @home.bath_room %> <%= @home.bath_room > 1? "Bathrooms" : "Bathroom" %>
						</div>
					</div>
				</div>

			</div>
		</div>

		<div class="col-md-4">
			<!-- reservation form -->
			<%= render 'swaps/form' %>

		</div>
	</div>

	<!-- about -->
	<hr>
	<div class="row">
		<div class="col-md-12 about-home">
			<h2>about this home</h2>
			<p><%= @home.summary %></p>
		</div>
	</div>

	<!-- amenities --><!--
	<div class="row">
		<div class="col-md-2">
			<p>Amenities</p>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-6">
					<ul class="amenities">
						<li class="<%= 'text-line-through' if !@home.is_air %>">airconditioning</li>
						<li class="<%= 'text-line-through' if !@home.is_heating %>">heating</li>
					</ul>
				</div>				
			</div>
		</div>
	</div> -->

	<!-- carousel -->
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div id="myCarousel" class="carousel slide" data-ride="carousel">
			  <!-- Indicators -->
			  <% if @photos %>
			  <ol class="carousel-indicators">
			  	<% @photos.each do |photo| %>
			    <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
			   <% end %>
			  </ol>
			  <% end %>

			  <!-- Wrapper for slides -->
			  <div class="carousel-inner" role="listbox">
			  	<% if @photos %>
			  		<% @photos.each do |photo| %>
			    <div class="item <%= 'active' if photo.id == @photos[0].id %>">
			      <%= image_tag photo.image.url() %>
			    </div>
			    <% end %>
			    <%end %>  
			  </div>

			  <!-- Left and right controls -->
			  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
			    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
			    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
		</div>
	</div>

	<br>
	<hr>
	<!-- map -->
	<div class="row">
		<div class="col-md-12">
			<div id="map"></div>

			<style>
				#map {
        			width: 100%;
        			height: 400px;
     			}
    		</style>

    		<script src="https://maps.googleapis.com/maps/api/js"></script>
    	        <script>
    			function initialize() {
    				var mapCanvas = document.getElementById('map');
    				var mapOptions = {
    					center: new google.maps.LatLng(<%= @home.latitude %>, <%= @home.longitude %>),
    					zoom: 14,
    					mapTypeId: google.maps.MapTypeId.ROADMAP
    				}
    				var map = new google.maps.Map(mapCanvas, mapOptions);
    			

    				var marker = new google.maps.Marker({
    					position: new google.maps.LatLng(<%= @home.latitude %>, <%= @home.longitude %>),

    				});

    				marker.setMap(map);
    			}
    			google.maps.event.addDomListener(window, 'load', initialize);
    			</script>

    			
		</div>

	</div>

	<!-- close by -->
	<hr>
	<h3>Near by</h3>
	<div class="row">
		<% for home in @home.nearbys(10) %>

		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading preview">
					<%= image_tag home.photos[0].image.url(:medium) %>
				</div>
				<div class="panel-body">
					<%= link_to home.listing_name, home %><br>
					(<%= home.distance.round(2) %> kms away)
				</div>
			</div>
		</div>
		<% end %>

	</div>
</div>

app/views/homes/update.html.erb
<h1>Homes#update</h1>
<p>Find me in app/views/homes/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homeswap</title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Abel|Roboto|Rochester" rel="stylesheet">

    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    

  </head>

  <body>

      <%= render 'shared/navbar' %>
      <div class="mtop"></div>
      <%= render 'shared/message' %>
    <div class="container">
    	<%= yield %>
  	</div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="mtop"></div>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_list.html.erb
<% if @photos %>
	<div class="row">
		<% @photos.each do |photo| %>
			<div class="col-md-4">
				<div class="panel panel-default">
					<div class="panel-heading preview">
						<%= image_tag photo.image.url() %>
					</div>
					<div class="panel-body">
						<span class="pull-right">
							<%= link_to photo, remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
						<i class="fa fa-times fa-lg"></i>
							<% end %>
						</span>
					</div>
				</div>
			</div>
		<% end %>

	</div>



	</div>

<% end %>

app/views/photos/destroy.js.erb
$('#photos').html("<%= j render 'photos/list' %>")

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">hideaway</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            
          <% if(!user_signed_in?) %>
            <li><%= link_to "Log In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          
          <% else %>
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %> <span class="caret"></span></a>



              <ul class="dropdown-menu">
                <li><%= link_to "Your Listings", homes_path %></li>
                <li><%= link_to "Your Swaps", your_swaps_path %></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Account Settings</a></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          
          <% end %>

          <li>
            <a href="#">
          <i class="fa fa-envelope-o" aria-hidden="true"></i> Messages</a>
          </li>
          <li>
            <a href="#">
          <i class="fa fa-home fa-lg" aria-hidden="true"></i> Swap</a>
          </li>

            
          </ul>
         
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/swaps/_form.html.erb
<%= form_for([@home, @home.swaps.new]) do |f| %>
	
	<div class="row">
		<div class="col-md-6">
			<label>Start</label>
			<%= f.text_field :start_date, readonly: 'true', placeholder: 'start Date', class: 'form-control' %>
		</div>
		<div class="col-md-6">
			<label>End</label>
			<%= f.text_field :end_date, readonly: 'true', placeholder: 'end Date', class: 'form-control', disabled: 'true' %>
		</div>
	</div>
	
	<!--<%= f.text_field :start_date %>
	<%= f.text_field :end_date %>-->
	<%= f.hidden_field :home_id, value: @home.id %>

	<h4><span id="message"></span></h4>
	
	<div id="preview" style="display: none">

		<table class="swap-table">
			<tbody>
				<tr>
					<td>Days</td>
					<td><span id="swap_days"></span></td>
				</tr>
			</tbody>
		</table>
	<br>
	</div>
	
	<%= f.submit "Request Swap", class: "btn btn-primary wide", id: "btn-book", disabled: 'true' %>
<% end %>

<script>

	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];

	}

	$(function() {

		unavailableDates = [];
	
		$.ajax({
			url: '/preload',
			data: {'home_id': <%= @home.id %>},
			dataType: 'json',
			success: function(data) {

				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
					}

				});

				$('#swap_start_date').datepicker({
						dateFormat: 'dd-mm-yy',
						minDate: 0,
						maxDate: '3m',
						beforeShowDay: unavailable,
						onSelect: function(selected) {
							$('#swap_end_date').datepicker("option", "minDate", selected);
							$('#swap_end_date').attr('disabled', false);

							var start_date = $(this).datepicker('getDate');
							var end_date = $('#swap_end_date').datepicker('getDate');
							var days = (end_date - start_date)/1000/60/60/24 + 1

							var input = {
								'start_date': start_date,
								'end_date': end_date,
								'home_id': <%= @home.id %>
							}

							$.ajax({
								url: "/preview",
								data: input,
								success: function(data) {

									if (data.conflict) {

										$('#message').text("This date is not available");
										$('#preview').hide();
										$('#btn-book').attr('disabled', true);

									} else {

										$('#preview').show();
										$('#btn-book').attr('disabled', false);

										
										$('#swap_days').text(days);

									}
								}
							});
						}
					});
				
					$('#swap_end_date').datepicker({
						dateFormat: 'dd-mm-yy',
						minDate: 0,
						maxDate: '3m',
						beforeShowDay: unavailable,
						onSelect: function(selected) {
							$('#swap_start_date').datepicker("option", "maxDate", selected);

							var start_date = $('#swap_start_date').datepicker('getDate');
							var end_date = $(this).datepicker('getDate');
							var days = (end_date - start_date)/1000/60/60/24 + 1


							var input = {
								'start_date': start_date,
								'end_date': end_date,
								'home_id': <%= @home.id %>
							}

							$.ajax({
								url: "/preview",
								data: input,
								success: function(data) {

									if (data.conflict) {
										$('#message').text("This date range is not available");
										$('#preview').hide();
										$('#btn-book').attr('disabled', true);
									} else {
						
										$('#preview').show();
										$('#btn-book').attr('disabled', false);

										$('#swap_days').text(days);


									}
								}

							});
						}
					});

			}

		});
	


	});


</script>

app/views/swaps/your_swaps.html.erb
<div class="row">
	<div class="col-md-3">
	<ul class="sidebar-list">
		<li class="sidebar-link"><%= link_to "Your Listing", homes_path, class: "sidebar-link" %>
		</li>
		<li class="sidebar-item"><%= link_to "Your Swaps", homes_path, class: "sidebar-link active" %>
		</li>
	</ul>
	</div>

	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
			Your Swaps
			</div>
			<div class="panel-body">
				<% @homes.each do |home| %>
				<% home.swaps.each do |swap| %>
					<div class="row">
						<div class="col-md-2">
							<%= swap.start_date.strftime('%v') %>
						</div>
						<div class="col-md-6">
							<%= link_to home_path(swap.home) do %>
								<%= image_tag swap.home.photos[0].image.url(:thumb) if swap.home.photos.length > 0 %>
							<% end %>
						</div>
						<div class="col-md-2">
							<%= link_to user_path(swap.home.user) do %>
								<%= image_tag avatar_url(trip.room.user), class: "img-circle avatar-medium" %>
							<% end %>
						</div>
						<div class="col-md-2 right">
							<h4>trip total here</h4>
						</div>	
					<hr>
				<% end %>
			<% end %>
			</div>
		</div>
	</div>
</div>